### ISSUE TITLE
update KDE runtime to 5.12

### ISSUE THREAD

**Issue by eszlari** [flathub/io.github.wereturtle.ghostwriter#1]

**Comment by wereturtle** [comment]
Would you please elaborate why this needs to happen now?  Is 5.11 being deprecated from FlatHub?

**Comment by eszlari** [comment]
https://github.com/KDE/flatpak-kde-runtime/commit/4d7a8d72983d9e86f5f5ce46d3524544c0ee6abe

**Comment by wereturtle** [comment]
Done!
