### ISSUE TITLE
Pandoc is out of date

### ISSUE THREAD

**Issue by RyanHir** [flathub/io.github.wereturtle.ghostwriter#11]
The current version of Pandoc is 2.19.2 while the one packaged is 2.2.1 (released in mid-2018). There are language features I wish to use that are only present in later versions of Pandoc that I am unable to use with this version. Is there a reason for holding back Pandoc?

**Comment by Aman9das** [comment]
Extremely sorry, wereturtle's repository switched to KDE, I was not aware of the change and wasn't notified about new releases. Updated version should be available on flathub soon.
