### ISSUE TITLE
Move pandoc to extension

### ISSUE THREAD

**Issue by Erick555** [flathub/io.github.wereturtle.ghostwriter#3]
Both pandoc binaries weight 122MB while whole app is 130MB. Pandoc isn't essential for this app to work so I think it would be good idea to move it to extension like `io.github.wereturtle.ghostwriter.pandoc`. Users may install it when needed then.

**Comment by Erick555** [comment]
@wereturtle any comment on this? Pandoc is optional dependency in [Arch](https://aur.archlinux.org/packages/ghostwriter/) and [Ubuntu](https://packages.ubuntu.com/disco/ghostwriter). Ghostwriter package weights about ~1.5MB in those distros while in flatpak it's 136.6 MB. This makes flatpak vastly inferior choice.

**Comment by taw00** [comment]
Crossposting the associated bug that is sitting in the ghostwriter queue: https://github.com/wereturtle/ghostwriter/issues/442
