### ISSUE TITLE
Inserting an iframe causes web browser to load it

### ISSUE THREAD

**Issue by SuborbitalPigeon** [flathub/io.github.wereturtle.ghostwriter#5]
If you put an iframe in a document with a 'src', the default web browser will load with that source. 

Example:

`<iframe src="https://www.w3schools.com"></iframe>`

Thanks to @will-jj for finding this.

**Comment by wereturtle** [comment]
I'm afraid that's just standard Chromium behavior.  If I turn that off, then you won't be able to click on links have your default browser open with them.  Some people will complain.  Turning that feature off might also involve turning off being able to load remote JavaScript files (like for MathJax).

Just...don't put in an iframe into your Markdown document?  :)
