### ISSUE TITLE
Update to the last version (ghostwriter 2.1.2 Latest on Mar 15)

### ISSUE THREAD

**Issue by felipehw** [flathub/io.github.wereturtle.ghostwriter#9]
Update to the last version (ghostwriter 2.1.2 Latest on Mar 15)

**Comment by Aman9das** [comment]
@barthalion @hfiguiere I am happy to take over maintainership

**Comment by barthalion** [comment]
FYI @wereturtle, I've invited @Aman9das to collaborators.

**Comment by felipehw** [comment]
@Aman9das updated!
Thanks :D
🎉🎉🎉🎉
